apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: praxis-form
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MoGh15/infra_x_projekt.git
    targetRevision: main
    path: chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: praxis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
